-- Phase 7 (Level 2): asynchronous AI interviews.
--
-- `interviews` (0004) already means a calendar-scheduled interview with a human
-- interviewer. This is a different thing — a candidate answering an AI on their
-- own time, from a single-use link — so it gets its own tables rather than more
-- nullable columns on that one.
--
-- Two guarantees are built into the schema rather than the application:
--
--   1. One token can only ever produce one session. The session row is created
--      AT ISSUE TIME and the token hash is UNIQUE on it, so "start a second
--      session" is not a check that can be raced past — there is no second row
--      to create.
--
--   2. The transcript is append-only. A question is immutable once asked, an
--      answer is immutable once given. Level 2 scores each rubric criterion
--      against a verbatim quote from this transcript; if the transcript could
--      be edited afterwards, a validated quote could silently stop matching and
--      the evidence check would be theatre.

-- ---------------------------------------------------------------------------
-- Token hashing
-- ---------------------------------------------------------------------------
-- The raw token is never stored. It is generated by the backend, handed to the
-- candidate once inside the link, and only its SHA-256 lands in the database.
--
-- This deliberately departs from `interviews.public_token`, which stores its
-- token in the clear. There the token only selects a time slot. Here the token
-- IS the authentication — it opens a live interview and everything the
-- candidate has already said — and recruiters can SELECT this table. A stored
-- plaintext token would let any org member resume any candidate's interview as
-- that candidate.
--
-- sha256() and convert_to() are both core PostgreSQL; no pgcrypto dependency,
-- so this resolves the same whether pgcrypto lives in `public` or `extensions`.
create or replace function public.ai_interview_token_hash(raw_token text)
  returns bytea language sql immutable strict
as $fn$
  select sha256(convert_to(raw_token, 'utf8'))
$fn$;

comment on function public.ai_interview_token_hash(text) is
  'SHA-256 of an interview link token. The backend hashes with hashlib.sha256(t.encode()).digest() — identical bytes.';

-- Legal status transitions, in one place so the guard trigger and any future
-- reader agree on what the lifecycle is.
--
--   issued           link handed out, nothing asked yet
--   in_progress      Q1 exists — the token is spent, the session is live
--   completed        every question answered; scoring may now run
--   scoring_rejected scoring ran and at least one evidence quote failed
--   scored           scoring ran and every quote matched the transcript
--
-- There is no 'expired' status. Expiry is `expires_at < now()` and is read, not
-- written — a stored flag would need a sweeper and would drift from the column
-- it duplicates. `scored` is terminal: once a valid score card exists, a later
-- bad re-score cannot demolish it.
create or replace function public.ai_interview_next_states(from_status text)
  returns text[] language sql immutable
as $fn$
  select case from_status
    when 'issued'           then array['in_progress']
    when 'in_progress'      then array['completed']
    when 'completed'        then array['scored', 'scoring_rejected']
    when 'scoring_rejected' then array['scored']
    else array[]::text[]
  end
$fn$;

-- ---------------------------------------------------------------------------
-- Sessions
-- ---------------------------------------------------------------------------
create table if not exists public.ai_interview_sessions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  candidate_id uuid not null references public.candidates(id) on delete cascade,
  role_id uuid references public.roles(id) on delete set null,

  token_hash bytea not null unique,            -- SHA-256; the raw token is not stored
  issued_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '72 hours'),
  consumed_at timestamptz,                     -- stamped when Q1 is written; write-once

  status text not null default 'issued',
  question_target int not null default 5,
  completed_at timestamptz,

  issued_by uuid references auth.users(id),
  created_at timestamptz not null default now(),

  constraint ai_sessions_status_check check (status in
    ('issued', 'in_progress', 'completed', 'scored', 'scoring_rejected')),
  constraint ai_sessions_target_check check (question_target between 1 and 20),
  constraint ai_sessions_window_check check (expires_at > issued_at)
);

create index if not exists idx_ai_sessions_org on public.ai_interview_sessions(organization_id);
create index if not exists idx_ai_sessions_candidate on public.ai_interview_sessions(candidate_id);
create index if not exists idx_ai_sessions_status on public.ai_interview_sessions(organization_id, status);

comment on column public.ai_interview_sessions.consumed_at is
  'When the token produced its first question. Consumption stops a SECOND session being minted; it does not stop this one resuming.';

-- ---------------------------------------------------------------------------
-- Turns
-- ---------------------------------------------------------------------------
-- One row per question. The question is written when it is generated and
-- BEFORE it is shown; the answer arrives later as an UPDATE. That ordering is
-- what makes a crash survivable: whatever the candidate saw is already on
-- record, so reopening the link re-serves the same question rather than
-- generating a different one and quietly rewriting history.
create table if not exists public.ai_interview_turns (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,               -- copied from the session by the gate trigger
  session_id uuid not null references public.ai_interview_sessions(id) on delete cascade,
  ordinal int not null,

  question_text text not null,
  asked_at timestamptz not null default now(),
  answer_text text,
  answered_at timestamptz,

  -- Provenance for DONE #4: which turn's answer this question was conditioned
  -- on, and what the model saw. Q1 has no source turn.
  source_turn_ordinal int,
  model text,

  constraint ai_turns_ordinal_check check (ordinal >= 1),
  constraint ai_turns_source_check check (source_turn_ordinal is null or source_turn_ordinal < ordinal)
);

-- The idempotency key. A double-submitted question or a duplicated request
-- collides here instead of forking the transcript.
create unique index if not exists uq_ai_turns_session_ordinal
  on public.ai_interview_turns(session_id, ordinal);
create index if not exists idx_ai_turns_org on public.ai_interview_turns(organization_id);

-- ---------------------------------------------------------------------------
-- Session guard
-- ---------------------------------------------------------------------------
create or replace function public.ai_interview_sessions_guard()
  returns trigger language plpgsql
as $fn$
begin
  if new.token_hash is distinct from old.token_hash then
    raise exception 'ai_interview_sessions: token_hash is immutable — issue a new session instead';
  end if;

  if new.organization_id is distinct from old.organization_id
     or new.candidate_id is distinct from old.candidate_id
     or new.role_id is distinct from old.role_id then
    raise exception 'ai_interview_sessions: a session cannot be reassigned to another tenant, candidate or role';
  end if;

  if old.consumed_at is not null and new.consumed_at is distinct from old.consumed_at then
    raise exception 'ai_interview_sessions: consumed_at is write-once (already %)', old.consumed_at;
  end if;

  if new.question_target is distinct from old.question_target and old.consumed_at is not null then
    raise exception 'ai_interview_sessions: the question count is fixed once the interview has started';
  end if;

  -- expires_at stays mutable ON PURPOSE. build.md DONE #2 is verified by
  -- backdating it on a real session row; a trigger that froze it would make
  -- the expiry path untestable without inserting a fake session.
  --
  -- Note for anyone doing that: ai_sessions_window_check is `expires_at >
  -- issued_at`, so expires_at CANNOT be dragged into the past on its own —
  -- issued_at has to move with it. Backdate the whole window (issued_at =
  -- now() - 80h, expires_at = now() - 8h), which is what an expired link
  -- actually is anyway. issued_at is left mutable for exactly this reason.

  if new.status is distinct from old.status
     and not (new.status = any (public.ai_interview_next_states(old.status))) then
    raise exception 'ai_interview_sessions: illegal transition % -> % (session %)',
      old.status, new.status, old.id;
  end if;

  return new;
end
$fn$;

drop trigger if exists ai_sessions_guard on public.ai_interview_sessions;
create trigger ai_sessions_guard before update on public.ai_interview_sessions
  for each row execute function public.ai_interview_sessions_guard();

-- ---------------------------------------------------------------------------
-- Turn gate
-- ---------------------------------------------------------------------------
create or replace function public.ai_interview_turns_gate()
  returns trigger language plpgsql
as $fn$
declare
  s public.ai_interview_sessions%rowtype;
  prev public.ai_interview_turns%rowtype;
begin
  -- FOR UPDATE serialises concurrent writes against one session, so two
  -- simultaneous submissions cannot both pass the "previous turn is answered"
  -- test below. The unique index on (session_id, ordinal) is the second line
  -- of defence, not the first.
  select * into s from public.ai_interview_sessions
    where id = coalesce(new.session_id, old.session_id)
    for update;
  if not found then
    raise exception 'ai_interview_turns: session % does not exist', new.session_id;
  end if;

  if tg_op = 'INSERT' then
    -- Never trust a caller-supplied tenant on a table whose RLS depends on it.
    new.organization_id := s.organization_id;

    if s.expires_at <= now() then
      raise exception 'ai_interview_turns: session % expired at %', s.id, s.expires_at;
    end if;
    if s.status not in ('issued', 'in_progress') then
      raise exception 'ai_interview_turns: session % is %, not accepting questions', s.id, s.status;
    end if;
    if new.ordinal > s.question_target then
      raise exception 'ai_interview_turns: ordinal % exceeds question_target % for session %',
        new.ordinal, s.question_target, s.id;
    end if;
    if btrim(coalesce(new.question_text, '')) = '' then
      raise exception 'ai_interview_turns: a turn must carry its question text';
    end if;
    -- The question is recorded before it is shown. Supplying the answer in the
    -- same statement would mean the question was never on record on its own,
    -- which is precisely the crash window this design closes.
    if new.answer_text is not null then
      raise exception 'ai_interview_turns: insert the question first, then answer it with an UPDATE';
    end if;
    new.answered_at := null;

    if new.ordinal > 1 then
      select * into prev from public.ai_interview_turns
        where session_id = new.session_id and ordinal = new.ordinal - 1;
      if not found then
        raise exception 'ai_interview_turns: turn % cannot exist before turn %',
          new.ordinal, new.ordinal - 1;
      end if;
      if prev.answer_text is null then
        raise exception 'ai_interview_turns: turn % is unanswered — question % is not due yet',
          prev.ordinal, new.ordinal;
      end if;
    end if;

    return new;
  end if;

  -- UPDATE ------------------------------------------------------------------
  if new.session_id is distinct from old.session_id
     or new.ordinal is distinct from old.ordinal then
    raise exception 'ai_interview_turns: a turn cannot be moved to another session or ordinal';
  end if;
  if new.question_text is distinct from old.question_text then
    raise exception 'ai_interview_turns: the question is immutable once asked';
  end if;
  new.organization_id := old.organization_id;
  new.asked_at := old.asked_at;

  if old.answer_text is not null then
    if new.answer_text is distinct from old.answer_text then
      raise exception 'ai_interview_turns: turn % of session % is already answered; the transcript is append-only',
        old.ordinal, old.session_id;
    end if;
    new.answered_at := old.answered_at;
    return new;
  end if;

  if new.answer_text is not null then
    if btrim(new.answer_text) = '' then
      raise exception 'ai_interview_turns: a blank answer is not an answer';
    end if;
    if s.expires_at <= now() then
      raise exception 'ai_interview_turns: session % expired at % — the answer window has closed',
        s.id, s.expires_at;
    end if;
    new.answered_at := now();
  end if;

  return new;
end
$fn$;

drop trigger if exists ai_turns_gate on public.ai_interview_turns;
create trigger ai_turns_gate before insert or update on public.ai_interview_turns
  for each row execute function public.ai_interview_turns_gate();

-- ---------------------------------------------------------------------------
-- Session advancement — the application never sets these by hand
-- ---------------------------------------------------------------------------
create or replace function public.ai_interview_advance_session()
  returns trigger language plpgsql
as $fn$
declare
  target int;
  answered int;
begin
  if tg_op = 'INSERT' then
    -- Writing Q1 is what spends the token. Defining consumption as a
    -- side effect of the first question — rather than a separate flag the
    -- backend has to remember to set — means a link cannot be half-consumed.
    update public.ai_interview_sessions
       set consumed_at = coalesce(consumed_at, now()),
           status = case when status = 'issued' then 'in_progress' else status end
     where id = new.session_id;
    return null;
  end if;

  if new.answer_text is null then
    return null;
  end if;

  select question_target into target
    from public.ai_interview_sessions where id = new.session_id;
  select count(*) into answered
    from public.ai_interview_turns
   where session_id = new.session_id and answer_text is not null;

  if answered >= target then
    update public.ai_interview_sessions
       set status = 'completed', completed_at = now()
     where id = new.session_id and status = 'in_progress';
  end if;

  return null;
end
$fn$;

drop trigger if exists ai_turns_advance on public.ai_interview_turns;
create trigger ai_turns_advance after insert or update of answer_text
  on public.ai_interview_turns
  for each row execute function public.ai_interview_advance_session();

-- ---------------------------------------------------------------------------
-- Reading the session
-- ---------------------------------------------------------------------------
-- Resume state, computed. Turns are strictly sequential and only the last one
-- can be unanswered, so the next ordinal is always answered_count + 1 — whether
-- the candidate is resuming a question they already saw or waiting on one that
-- has yet to be generated. `next_question_text` distinguishes the two: non-null
-- means re-serve exactly this, null means generate it.
create or replace view public.ai_interview_session_state
with (security_invoker = on) as
select
  s.id                as session_id,
  s.organization_id,
  s.candidate_id,
  s.role_id,
  s.status,
  s.question_target,
  s.issued_at,
  s.expires_at,
  s.consumed_at,
  s.completed_at,
  (s.expires_at <= now())                       as is_expired,
  t.asked_count,
  t.answered_count,
  case when t.answered_count < s.question_target
       then t.answered_count + 1 end            as next_ordinal,
  t.pending_question                            as next_question_text,
  (s.expires_at > now()
   and s.status in ('issued', 'in_progress'))   as is_open
from public.ai_interview_sessions s
left join lateral (
  select
    count(*)                                            as asked_count,
    count(*) filter (where answer_text is not null)     as answered_count,
    max(question_text) filter (where answer_text is null) as pending_question
  from public.ai_interview_turns where session_id = s.id
) t on true;

-- The candidate's own words, in order. This is the corpus every rubric
-- evidence quote is checked against (0008) and the text that gets embedded as
-- a transcript (0009). Questions are excluded deliberately: a criterion that
-- "proves" itself by quoting the interviewer's own question has proved nothing.
create or replace function public.ai_interview_transcript(p_session uuid)
  returns text language sql stable
as $fn$
  select string_agg(answer_text, E'\n\n' order by ordinal)
    from public.ai_interview_turns
   where session_id = p_session and answer_text is not null
$fn$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.ai_interview_sessions enable row level security;
alter table public.ai_interview_turns enable row level security;

-- Read-only for recruiters, and no write policy at all.
--
-- The candidate is unauthenticated — they hold a token, not a JWT — so every
-- candidate-side read and write goes through the backend's service role keyed
-- by that token, exactly as the existing /api/public/schedule/{token} endpoints
-- do. `authenticated` therefore never needs to write here, and must not: a
-- recruiter who could INSERT or UPDATE a turn could compose a candidate's
-- answer, and every evidence quote on the score card is validated against
-- precisely these rows.
drop policy if exists ai_sessions_select on public.ai_interview_sessions;
create policy ai_sessions_select on public.ai_interview_sessions
  for select using (public.is_org_member(organization_id));

drop policy if exists ai_turns_select on public.ai_interview_turns;
create policy ai_turns_select on public.ai_interview_turns
  for select using (public.is_org_member(organization_id));
